DROP TABLE IF EXISTS posts CASCADE;

CREATE TABLE posts(
    id SERIAL PRIMARY KEY NOT NULL,
    engWord VARCHAR(255) NOT NULL,
    transWord VARCHAR(255) NOT NULL,
    definition TEXT,
    user_id INTEGER REFERENCES users(id)
);